### ISSUE TITLE
Add License for Qlack.

### ISSUE THREAD

**Issue by NexusSfan** [benji123good/qlackos#1]
By not adding a license, you are saying that others cannot fork your repo.
Read more here:
https://choosealicense.com/no-permission/

Hopefully you will add a license to your OS repo.

**Comment by benji123good** [comment]
I seriously don't care like at all

**Comment by benji123good** [comment]
what do u even mean

**Comment by benji123good** [comment]
Yeah I don't want pepole copying qlack

**Comment by benji123good** [comment]
And it says if I have a license they can do dat

**Comment by NexusSfan** [comment]
> I seriously don't care like at all

By Copying, they mean that people can Modify your code and make your own versions of it.
You have to care, or your project WILL fail.

**Comment by benji123good** [comment]
Qlack OS Recived ur request... Please Tell Us What Licens you Want Us To Get

**Comment by NexusSfan** [comment]
For something like what you are doing I would recommend a GNU License for your project.

**Comment by benji123good** [comment]
k done

**Comment by benji123good** [comment]
Where done And We Are Now Adding It
